"""
core/collector.py
=================
Safe command execution abstraction for SENTINELAUDIT.

SECURITY CONTRACT
-----------------
1. Only commands explicitly registered in a platform's ALLOWED_COMMANDS map
   may be executed.
2. shell=True is NEVER used.
3. Arbitrary user strings are NEVER accepted as commands.
4. Commands generated by an LLM are NEVER executed.
5. stdout, stderr, and return code are always captured.
6. Timeouts and common OS errors are handled gracefully.

Usage pattern (platform adapters)
----------------------------------
    from core.collector import CommandCollector, CollectorResult

    ALLOWED_COMMANDS = {
        "check_firewall": ["ufw", "status"],
        "list_users":     ["cat", "/etc/passwd"],
    }

    collector = CommandCollector(allowed=ALLOWED_COMMANDS)
    result    = collector.run("check_firewall")

    if result.ok:
        print(result.stdout)
    else:
        print(result.error)
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from typing import Optional

# Default timeout in seconds for any single command.
DEFAULT_TIMEOUT: int = 30


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------

@dataclass
class CollectorResult:
    """
    The outcome of a single command execution.

    Attributes
    ----------
    command_key : The logical name used to look up the command.
    argv        : The actual list of strings passed to subprocess.
    stdout      : Captured standard output (stripped).
    stderr      : Captured standard error (stripped).
    returncode  : Process exit code, or None if the process never started.
    error       : Human-readable error message if execution failed.
    timed_out   : True if the command exceeded the timeout.
    not_found   : True if the executable was not found on the system.
    permission_denied : True if the OS denied execution.
    """

    command_key: str
    argv: list[str]
    stdout: str = ""
    stderr: str = ""
    returncode: Optional[int] = None
    error: str = ""
    timed_out: bool = False
    not_found: bool = False
    permission_denied: bool = False

    @property
    def ok(self) -> bool:
        """True if the command ran and exited with code 0."""
        return (
            self.returncode == 0
            and not self.timed_out
            and not self.not_found
            and not self.permission_denied
        )

    @property
    def evidence_text(self) -> str:
        """
        Convenience property: returns stdout if present, otherwise stderr.
        Useful for populating Finding.evidence.
        """
        return self.stdout if self.stdout else self.stderr

    def __str__(self) -> str:
        status = "OK" if self.ok else f"ERROR({self.error or self.returncode})"
        return f"CollectorResult[{self.command_key}] {status}"


# ---------------------------------------------------------------------------
# CommandCollector
# ---------------------------------------------------------------------------

class CommandCollector:
    """
    Executes pre-approved, read-only commands safely.

    Parameters
    ----------
    allowed : dict[str, list[str]]
        A mapping of logical command key → argv list.
        Example: {"firewall_status": ["ufw", "status"]}
    timeout : int
        Maximum seconds to wait for any single command. Default: 30.
    """

    def __init__(
        self,
        allowed: dict[str, list[str]],
        timeout: int = DEFAULT_TIMEOUT,
    ) -> None:
        if not isinstance(allowed, dict):
            raise TypeError("'allowed' must be a dict mapping str → list[str].")
        self._allowed: dict[str, list[str]] = allowed
        self._timeout: int = timeout

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def available_commands(self) -> list[str]:
        """Return the list of registered command keys."""
        return list(self._allowed.keys())

    def run(self, command_key: str) -> CollectorResult:
        """
        Execute the command registered under *command_key*.

        Parameters
        ----------
        command_key : str
            Must be a key present in the ``allowed`` mapping supplied at
            construction time.

        Returns
        -------
        CollectorResult
            Always returns a result object; never raises.

        Raises
        ------
        KeyError
            If *command_key* is not in the allowed commands mapping.
            This is intentional — callers must only request known keys.
        """
        if command_key not in self._allowed:
            raise KeyError(
                f"Command key '{command_key}' is not in the allowed commands list. "
                f"Available keys: {sorted(self._allowed.keys())}"
            )

        argv: list[str] = self._allowed[command_key]
        result = CollectorResult(command_key=command_key, argv=argv)

        self._execute(argv, result)
        return result

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _execute(self, argv: list[str], result: CollectorResult) -> None:
        """
        Run *argv* via subprocess and populate *result* in-place.

        shell=True is deliberately NEVER used here.
        """
        try:
            proc = subprocess.run(
                argv,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                shell=False,          # NEVER True
                timeout=self._timeout,
                text=True,
            )
            result.stdout = proc.stdout.strip()
            result.stderr = proc.stderr.strip()
            result.returncode = proc.returncode

        except subprocess.TimeoutExpired:
            result.timed_out = True
            result.error = (
                f"Command '{' '.join(argv)}' timed out after {self._timeout}s."
            )

        except FileNotFoundError:
            result.not_found = True
            result.error = (
                f"Executable '{argv[0]}' not found on this system."
            )

        except PermissionError:
            result.permission_denied = True
            result.error = (
                f"Permission denied when trying to run '{argv[0]}'."
            )

        except OSError as exc:
            result.error = f"OS error running '{' '.join(argv)}': {exc}"


# ---------------------------------------------------------------------------
# Convenience factory
# ---------------------------------------------------------------------------

def make_collector(
    allowed: dict[str, list[str]],
    timeout: int = DEFAULT_TIMEOUT,
) -> CommandCollector:
    """
    Factory function — preferred entry point for platform adapters.

    Example
    -------
    collector = make_collector({
        "firewall_status": ["ufw", "status"],
        "kernel_version":  ["uname", "-r"],
    })
    """
    return CommandCollector(allowed=allowed, timeout=timeout)
