import type { Finding, FixItem, PlatformData } from "@/lib/audit-data"

function counts(findings: Finding[]) {
  const pass = findings.filter((f) => f.status === "PASS").length
  const fail = findings.filter((f) => f.status === "FAIL").length
  const unknown = findings.filter((f) => f.status === "UNKNOWN").length
  return { pass, fail, unknown, total: findings.length }
}

/** Structured, machine-readable report — the artifact a pipeline would consume. */
export function buildReportJson(data: PlatformData, generatedAt: string): string {
  const summary = counts(data.findings)
  const report = {
    schema: "cis-audit-agent/report@1",
    generated_at: generatedAt,
    platform: data.meta.id,
    benchmark: data.meta.benchmark,
    target: data.target,
    safety_model: {
      access: "read-only",
      command_allowlist: data.allowlist,
      prioritizer_can_change_verdicts: false,
      determinism: "temperature=0; ties broken by rule_id",
    },
    summary,
    findings: data.findings,
    remediation_plan: data.fixList,
  }
  return JSON.stringify(report, null, 2)
}

/** Human-readable report — the artifact a person reviews and acts on. */
export function buildReportMarkdown(data: PlatformData, generatedAt: string): string {
  const { target, findings, fixList, meta } = data
  const s = counts(findings)
  const line = (f: Finding) =>
    `| \`${f.rule_id}\` | ${f.status} | ${f.severity_hint} | ${f.title} | \`${f.evidence.replace(/\|/g, "\\|")}\` |`
  const fixLineItem = (f: FixItem) =>
    [
      `### ${f.priority}. ${f.finding}`,
      ``,
      `- **Rule:** \`${f.rule_id}\` · **Severity:** ${f.severity} · **Category:** ${f.category}`,
      `- **Why it matters:** ${f.why_it_matters}`,
      `- **Evidence:** \`${f.evidence_ref}\``,
      `- **Fix:**`,
      "  ```bash",
      `  ${f.fix_command}`,
      "  ```",
    ].join("\n")

  return [
    `# CIS Audit Report — ${meta.label}`,
    ``,
    `- **Benchmark:** ${meta.benchmark}`,
    `- **Target:** \`${target.host}\` (${target.os}, ${target.kernel})`,
    `- **Transport:** ${target.transport} · **User:** ${target.user}`,
    `- **Generated:** ${generatedAt}`,
    `- **Access model:** read-only (fixed command allowlist, no mutating commands executed)`,
    ``,
    `## Summary`,
    ``,
    `| Total | Pass | Fail | Unknown |`,
    `| --- | --- | --- | --- |`,
    `| ${s.total} | ${s.pass} | ${s.fail} | ${s.unknown} |`,
    ``,
    `## Findings`,
    ``,
    `| Rule | Status | Severity | Title | Evidence |`,
    `| --- | --- | --- | --- | --- |`,
    ...findings.map(line),
    ``,
    `## Remediation plan (worst-first)`,
    ``,
    `> Every item is grounded in the evidence above. A human reviews and runs these — the agent never changes the system.`,
    ``,
    ...fixList.map(fixLineItem),
    ``,
    `---`,
    `_Generated by CIS Audit Agent. Verdicts are deterministic; the prioritizer only ranks and explains._`,
    ``,
  ].join("\n")
}

/** Trigger a client-side download of a text artifact. */
export function downloadText(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
