"""Report generation: report.json (machine-readable) and report.md (human).

The JSON is the evidence record; the Markdown is what an administrator actually
executes fixes from. Both are generated from the same :class:`AuditReport`, so
they can never disagree.

Everything except ``generated_at`` is derived deterministically from the
findings, and ``fingerprint`` is a SHA-256 over exactly that stable payload --
so "did this run drift?" is a string comparison, not an eyeball diff.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from .models import FAIL, PASS, UNKNOWN, AuditReport, Finding

SCHEMA_VERSION = "1.0"
TOOL_VERSION = "1.0.0"

_STATUS_MARK = {PASS: "PASS", FAIL: "FAIL", UNKNOWN: "UNKN"}


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def timestamp_slug() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def build_report(
    *,
    platform: str,
    target: dict[str, object],
    findings: list[Finding],
    fix_list,
    commands,
    summary: dict[str, object],
    score: dict[str, object],
    notes: list[str],
) -> AuditReport:
    report = AuditReport(
        schema_version=SCHEMA_VERSION,
        tool_version=TOOL_VERSION,
        generated_at=utc_now(),
        target=target,
        platform=platform,
        summary=summary,
        score=score,
        findings=findings,
        fix_list=fix_list,
        commands=commands,
        notes=notes,
    )
    report.fingerprint = report.compute_fingerprint()
    return report


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------


def write_json(report: AuditReport, path: str) -> str:
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(report.to_dict(), handle, indent=2, ensure_ascii=False, sort_keys=False)
        handle.write("\n")
    return path


def write_markdown(report: AuditReport, path: str, feeds: dict[str, list[str]]) -> str:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(render_markdown(report, feeds))
    return path


def _fence(text: str) -> str:
    body = text.strip() or "(no output)"
    return "```\n" + body + "\n```"


def render_markdown(report: AuditReport, feeds: dict[str, list[str]]) -> str:
    out: list[str] = []
    w = out.append

    summary = report.summary
    score = report.score
    by_sev = summary["failed_by_severity"]  # type: ignore[index]

    w("# SentinelAudit Report\n")
    w(f"**Target:** `{report.target.get('label')}` "
      f"(transport: {report.target.get('transport')}, platform: {report.platform})  ")
    w(f"**Generated:** {report.generated_at}  ")
    w(f"**Fingerprint:** `{report.fingerprint}`  ")
    w(f"**Tool:** SentinelAudit {report.tool_version} "
      f"(schema {report.schema_version})\n")
    w("> The fingerprint is a SHA-256 over every part of this report except the")
    w("> timestamp. Two runs against an unchanged target produce the same value.\n")

    # -- score ------------------------------------------------------------
    w("## Security score\n")
    w(f"### {score['value']}/100 (grade {score['grade']})\n")
    w("| Severity | Failing |")
    w("| --- | --- |")
    for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
        w(f"| {sev} | {by_sev[sev]} |")  # type: ignore[index]
    w("")
    w(f"- Rules evaluated: **{summary['rules_evaluated']}**")
    w(f"- Passed: **{summary['passed']}** &nbsp;|&nbsp; "
      f"Failed: **{summary['failed']}** &nbsp;|&nbsp; "
      f"Unknown: **{summary['unknown']}**")
    w(f"- {score['coverage_note']}")
    w(f"- Deduction weights: {score['weights']}\n")

    # -- fix list ---------------------------------------------------------
    w("## Prioritized remediation plan\n")
    if not report.fix_list:
        w("No failing checks. Nothing to remediate.\n")
    else:
        w("Ordered by severity, then rule ID. Every item below traces to one "
          "rule, one command, and one captured evidence snippet.\n")
        for item in report.fix_list:
            w(f"### {item.priority}. [{item.severity}] {item.rule_id} — {item.category}\n")
            w(f"**Finding.** {item.finding}\n")
            w(f"**Why it matters.** {item.why_it_matters}")
            if item.explanation_source == "llm":
                w("\n<sub>Explanation generated by an LLM from the structured "
                  "finding. The verdict, severity, ordering and fix command "
                  "below are deterministic.</sub>")
            w("")
            w(f"**Evidence** (`{item.command}`):\n")
            w(_fence(item.evidence))
            w("")
            w("**Fix:**\n")
            w(_fence(item.fix_command))
            w("")
            w(f"<sub>evidence_ref: `{item.evidence_ref}`</sub>\n")

    # -- findings ---------------------------------------------------------
    w("## All findings\n")
    w("| Rule | Control | Status | Severity | Title | Evidence (first line) |")
    w("| --- | --- | --- | --- | --- | --- |")
    for f in report.findings:
        first = (f.evidence.splitlines() or [""])[0].replace("|", "\\|")
        if len(first) > 70:
            first = first[:67] + "..."
        w(f"| `{f.rule_id}` | {f.control_id} | **{_STATUS_MARK[f.status]}** | "
          f"{f.severity} | {f.title} | `{first}` |")
    w("")

    # -- unknowns ---------------------------------------------------------
    unknowns = [f for f in report.findings if f.status == UNKNOWN]
    w("## Unknown verdicts\n")
    if not unknowns:
        w("Every rule reached a PASS or FAIL verdict on this target.\n")
    else:
        w("These checks could not be adjudicated. They are reported as UNKNOWN "
          "with a reason rather than guessed at, and they do not affect the "
          "score.\n")
        for f in unknowns:
            w(f"- **`{f.rule_id}` {f.title}** — {f.reason or 'no reason recorded'}  ")
            w(f"  <sub>command: `{f.command}`</sub>")
        w("")

    # -- passed -----------------------------------------------------------
    passed = [f for f in report.findings if f.status == PASS]
    if passed:
        w("## Passing checks\n")
        w("Recorded for completeness -- a passing check needs no remediation.\n")
        for f in passed:
            w(f"- `{f.rule_id}` {f.title} — {f.evidence.splitlines()[0] if f.evidence else ''}")
        w("")

    # -- command log ------------------------------------------------------
    w("## Command log\n")
    w("Every command below came from the fixed allowlist and is strictly "
      "read-only. Each is tagged with the rules it feeds.\n")
    w("| Command | Exit | Available | Feeds |")
    w("| --- | --- | --- | --- |")
    for c in report.commands:
        rules = ", ".join(feeds.get(c.command_id, [])) or "-"
        display = c.display.replace("|", "\\|")
        w(f"| `{display}` | {c.exit_code} | {'yes' if c.available else 'no'} | {rules} |")
    w("")

    if report.notes:
        w("## Notes\n")
        for note in report.notes:
            w(f"- {note}")
        w("")

    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Report directory helpers
# ---------------------------------------------------------------------------


def save(report: AuditReport, feeds: dict[str, list[str]], out_dir: str) -> tuple[str, str]:
    os.makedirs(out_dir, exist_ok=True)
    slug = timestamp_slug()
    json_path = os.path.join(out_dir, f"audit_{slug}.json")
    md_path = os.path.join(out_dir, f"audit_{slug}.md")
    write_json(report, json_path)
    write_markdown(report, md_path, feeds)
    return json_path, md_path


def latest_report(out_dir: str, exclude: str | None = None) -> str | None:
    """Most recent audit_*.json in ``out_dir``, for --reaudit."""
    if not os.path.isdir(out_dir):
        return None
    candidates = sorted(
        name for name in os.listdir(out_dir)
        if name.startswith("audit_") and name.endswith(".json")
    )
    if exclude:
        exclude_name = os.path.basename(exclude)
        candidates = [c for c in candidates if c != exclude_name]
    if not candidates:
        return None
    return os.path.join(out_dir, candidates[-1])
